# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'notejam:$(build.buildId)'

steps:
- script: docker build -f flask/Dockerfile -t $(imageName) flask/.
  displayName: 'docker build'
- script: docker tag $(imageName) techniumlabs.azurecr.io/$(imageName)
  displayName: 'docker tag'
- script: docker login -u $(registryUsername) -p $(registryPassword) $(registryUsername).azurecr.io
- script: docker push techniumlabs.azurecr.io/$(imageName)
  displayName: 'docker push'