version: 0.2

phases:
  build:
    commands:
      - cd laravel/notejam
      - touch app/database/notejam.db
      - composer install --no-interaction --prefer-dist
      - php artisan migrate
      - ./vendor/bin/phpunit --verbose
