#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notejam
  template:
    metadata:
      labels:
        app: notejam
    spec:
      containers:
      - name: notejamserver
        image: ACRNotejam.azurecr.io/notejamserver
        ports:
        - containerPort: 5000
          hostPort: 5000
      imagePullSecrets:      
       - name: acrcred
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: notejamscaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: notejam
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
---
kind: Service
apiVersion: v1
metadata:
  name: notejamservice
spec:
  selector:
    app: notejam
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
  #loadBalancerSourceRanges:
  #- ... add IPs to allow limited access
  externalIPs:
  - 13.93.71.183
  