service: notejam

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: notejam.wsgi.application
    packRequirements: false
  pythonRequirements:
    #dockerizePip: non-linux
    dockerizePip: true
    dockerFile: Dockerfile

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage,'dev'}
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - s3:GetObject
       - s3:PutObject
      Resource: "arn:aws:s3:::*"
  vpc:
    subnetIds:
      Fn::Split:
        - ','
        - Fn::ImportValue: "notejam-Public-Subnets-${self:provider.stage}"
    securityGroupIds:
      - Fn::ImportValue: "notejam-RDSAccessGroup-${self:provider.stage}"
      - Fn::ImportValue: "notejam-Default-SG-${self:provider.stage}"

package:
  exclude:
    - requirements.txt
    - serverless.yml
    - package.json
    - package-lock.json
    - node_modules/**
    - .serverless/**

functions:
  app:
    name: notejam-${self:provider.stage}
    handler: wsgi_handler.handler
    timeout: 15
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  initdb:
    name: notejam-initdb-${self:provider.stage}
    timeout: 40
    handler: create_db.handle