version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - echo Build started on `date`
      - cd flask/
      - pip install -r requirements.txt -t build/
  pre_build:
    commands:
      - echo "[+] Running tests..."
      - python -m unittest tests
  build:
    commands:
      - echo "Build started"
      - echo "[+] Creating DB schemas..."
      - python db.py
      - echo "Copy python files"
      - cp runserver.py build/
artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no
