version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - echo Build started on `date`
      - pip install -r flask/requirements.txt
  pre_build:
    commands:
      - echo "[+] Running tests..."
      - python -m unittest tests
