version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - echo Build started on `date`
      - pip install -r flask/requirements.txt
  pre_build:
    commands:
      - echo "[+] Running tests..."
      - cd flask/
      - python -m unittest tests
      - echo "[+] Creating DB schemas..."
      - python db.py
  build:
    commands:
      - echo "Build started"
      - python runserver.py
